### ISSUE TITLE
Links to blogs

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#10]
There are some classic blogs, eg https://blogs.sap.com/2016/02/05/fanning-the-flames-prefixing-variableattribute-names/ for https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#avoid-encodings-esp-hungarian-notation-and-prefixes  that might be worth linking for providing more background and dicussion.

Again, not sure how to format/present this in the document, same issue as #3

**Comment by HrFlorianHoffmann** [comment]
Definitely worth linking. I think the [AvoidEncodings sub-page](https://github.com/SAP/styleguides/blob/master/clean-abap/sub-sections/AvoidEncodings.md) is a good place for this. If there is no consensus on a topic, it has been our aim to at least explain the positions to enable teams to decide on their own.

**Comment by larshp** [comment]
perfect 👍

**Comment by larshp** [comment]
fix part of https://github.com/SAP/styleguides/pull/9 which is not merged yet
