### ISSUE TITLE
S/4HANA Style Guide

### ISSUE THREAD

**Issue by KnutStargardt** [SAP/styleguides#104]
Maybe it should be mentioned that Clean ABAP is now the official style guide for SAP S/4HANA.

Kind regards,
Knut

**Comment by HrFlorianHoffmann** [comment]
Where and how?

Right at the start is a little too prominent, I think. My aim was to keep this intro extremely short:

> Clean ABAP
> This guide is an adoption of Robert C. Martin's Clean Code for ABAP.
> The Cheat Sheet is a print-optimized version.

What would be a better place?

**Comment by HrFlorianHoffmann** [comment]
Suggest to close this with https://github.com/SAP/styleguides/pull/155
