### ISSUE TITLE
recommend lowercase writing

### ISSUE THREAD

**Issue by haexhub** [SAP/styleguides#108]
Hi,

I'm glad to see, that even SAP found their way to clean code developer. 
Please consider to recommand lowercase typing for abap syntax. It's proven by different studies, that reading text in lowercase is much faster than uppercase. If I find the studies I will update this.
In one SAP documentation I found the explanation, why SAP recommand uppercase: 
If code is printed out, it's better to read. 
First, who ever printed code???
Second, as many studies already prove, it's easier for humans to read text in lowercase, compared to uppercase. So the explanation is wrong too.
Would be great if this would find the way in the official style guide as well.

**Comment by HrFlorianHoffmann** [comment]
We discussed this in short in the section [Use your Pretty Printer team settings](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#use-your-pretty-printer-team-settings) and in length in the article [Upper vs. Lower Case](https://github.com/SAP/styleguides/blob/master/clean-abap/sub-sections/UpperVsLowerCase.md).

In short:
> In summary, we can only recommend teams to discuss this and agree on one common style.
