### ISSUE TITLE
Prefer inline to up-front declarations

### ISSUE THREAD

**Issue by mAltr** [SAP/styleguides#116]
I personal fully agree with this, but maybe we can add a comment like "to not break the logic of complex legacy code". If you add in the middle of a 800 lines spaghetti code function suddenly inline declaration it might getting more and more unreadable.

**Comment by HrFlorianHoffmann** [comment]
Not against it, but not sure where and how to put it. The same applies to a selection of other recommendations as well, right? So maybe add something to a more general section like https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#how-to-refactor-legacy-code?

**Comment by jwigert** [comment]
I created a pull request #120 with my suggested update.

**Comment by thomham** [comment]
Since #120 is solved, this one may also be considered solved? @HrFlorianHoffmann
