### ISSUE TITLE
Recommended way to handle errors in mass operations

### ISSUE THREAD

**Issue by system91a** [SAP/styleguides#117]
Hi colleagues,

your guidelines are very helpful so far. But I could not find any recommendation for error handling during mass operations. How should an API tell the caller, that one of many operations failed (and why it fails)?
For example if I implement a method, which adds multiple items to a shopping card: In this case it make sense to continue adding the other items although adding one item may fail. The caller of this API is probably wants to know, which items failed and why to give feedback to the end user (or do other stuff). 

Exporting an additional message table works, but is not really nice in my opinion. Do you have any suggestions for this?

Thanks and best regards,
Heiko

**Comment by HrFlorianHoffmann** [comment]
The section https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#return-export-or-change-exactly-one-parameter gets pretty near to the kind of mass operation you describe:

```
TYPES:
  BEGIN OF check_result,
    result      TYPE result_type,
    failed_keys TYPE /bobf/t_frw_key,
    messages    TYPE /bobf/t_frw_message,
  END OF check_result.

METHODS check_business_partners
  IMPORTING
    business_partners TYPE business_partners
  RETURNING
    VALUE(result)     TYPE check_result.
```

While the method `check_business_partners` provides a check `result` as primary return value, it also returns details on what exactly didn't work and why.

**Comment by system91a** [comment]
This one is good. I guess I missed it. Thank you very much!
