### ISSUE TITLE
Make sure alternatives are comparable

### ISSUE THREAD

**Issue by weloli** [SAP/styleguides#149]
In [this chapter](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#Prefer-functional-to-procedural-language-constructs) it is recommended to use

```ABAP
DATA(line) = value_pairs[ name = 'A' ].
```
instead of 
```ABAP
READ TABLE value_pairs INTO DATA(line) WITH KEY name = 'A'.
```

Unfortunately the variants are only equivalent if it is guaranteed that a line with name = 'A' exists, which is normally not the case. As soon as the table is empty or does not contain a line with name = 'A', the recommended variant results in an exception (CX_SY_ITAB_LINE_NOT_FOUND), but READ TABLE works fine (resulting in an empty line).

A variant to avoid exceptions would be
```ABAP
DATA(line) = COND #( WHEN line_exists( value_pairs[ name = 'A' ] ) THEN value_pairs[ name = 'A' ] ).
```
but now the argument is gone that this is shorter and comes more natural.
Catching the exception would also be ugly.

**Comment by cgolde** [comment]
If it is okay that the result is empty, you could use:

`DATA(line) = VALUE #( value_pairs[ name = ‚A‘ ] OPTIONAL ).`

**Comment by HrFlorianHoffmann** [comment]
How about adding both variants as suggested in #149?
