### ISSUE TITLE
Could I translate Clean ABAP into Chinese?

### ISSUE THREAD

**Issue by hhelibeb** [SAP/styleguides#152]
I have read and written some Chinese documents on ABAP code style, but no document is better than  Clean ABAP.
I believe a Chinese version will be helpful to many developers. So I want to translate it into Chinese, if i am allowed.
And I am not sure about the way. Should I create a PR contains CleanABAP_zh_CN.md or just create a new repo named Clean ABAP - Chinese version?

**Comment by HrFlorianHoffmann** [comment]
Your contribution would be greatly appreciated. Some months back we came to the same conclusion, that a Chinese translation would help a lot of ABAPers, and initiated a Chinese translation of the then-actual state of Nov 14, 2019. Then came Corona and I simply lost track of this. :-(

I [just merged](https://github.com/SAP/styleguides/pull/153) the last version that our translators sent us, making the document available under https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP_zh.md.

**Comment by hhelibeb** [comment]
Good news! Glad to see there is already a Chinese translation. I will do the things following your advice.
* Check and fix broken links. I think it can be done by a script. I may try to do it this weekend.
* Rework language that doesn't fit. I think an important work is that comparing CleanABAP_zh with 代码整洁之道 (The Chinese version of Clean Code) and other Chinese technical books to find what the difference is and which one is better.
