### ISSUE TITLE
Can I translate the style guides to Spanish?

### ISSUE THREAD

**Issue by gabrielbaca** [SAP/styleguides#159]
I am an ABAP developer who has been closely following the Clean ABAP guidelines for about 1 year. I'd like to contribute back to all the value it has provided me by making it available to many of my coworkers who are not as proficient in English. Can I translate it to Spanish? And if so, is it as simple as forking the repository?

Thanks!

**Comment by HrFlorianHoffmann** [comment]
Oh man, sorry, I totally did not see this issue! 😥

In case you are still interested: Yes, you are very welcome to translate this guide to Spanish. Simply fork the repository, do the translation in the same way as the ones that are already there, i.e. [with language-suffixed filenames](https://github.com/SAP/styleguides/tree/main/clean-abap), and supply it as a pull request.

We will have somebody proof-read the text and check the links and structural formatting, so admission of the pull request may take a little longer, but that's all.

If a complete translation is too much for you alone, you can also set up a fork and invite others to help along.

**Comment by gabrielbaca** [comment]
No worries, thanks for your comments! I lost some progress a while ago when my laptop died on me (and I didn't commit a lot), but anyways I restarted the translation since the main branch is way ahead now. I'll create a push request once the main document is usable.

**Comment by gabrielbaca** [comment]
I submitted pull request #197 related to this issue.

**Comment by bjoern-jueliger-sap** [comment]
Appears to be done with #197.
