### ISSUE TITLE
Where to declare global type: abstract class or interface?

### ISSUE THREAD

**Issue by Suncatcher** [SAP/styleguides#163]
Recently I asked [this question on SO](https://stackoverflow.com/questions/62758463/class-or-interface-for-declaring-global-types) but I am still confused. Which approach is better to reuse?

Similarly to [constant approach](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#prefer-enumeration-classes-to-constants-interfaces) in styleguides Philipp recommended me to use abstract classes but here I see the complication: 

![image](https://user-images.githubusercontent.com/6388034/87799807-552d5b80-c856-11ea-9eec-da0bfbc5e100.png)

For self-defined types I cannot change the visibility, Philipp suggested the way to overcome this limitation by declaring types in code, but I consider this is cumbersome to redefine code section each time when I want to add type.

If this limitation was introduced then by SAP opinion abstract classes are not intended for type reuse. How do you think?

Up till now I see interfaces a better option to declare types. Is it?

**Comment by pokrakam** [comment]
Classes are a good option for the same reason already explained in the Constants section. 
SE24 is the limitation here, not abstract classes. In code you can change visibility. Switch to the source-code based editor (or use Eclipse) and move it to the public section. There's nothing cumbersome about that, SE24 is just a frontend that does the same. It's worth learning to write native code, it's much quicker once you learn the syntax properly, especially with Eclipse.

**Comment by Suncatcher** [comment]
> SE24 is the limitation here, not abstract classes

very dumb limitation, indeed. 

I know how to to write native code and I know ADT, but on the current customer they have no ADT support

**Comment by pokrakam** [comment]
My sympathies on not having ADT :(  I tend to use the source code editor in those situation. 

I can see the reason for the limitation. Fixed types in SE24 are stored in a table and the class code is generated from this. Once you start adding complex types in code, then SE24 would have to start modifying user code instead of just generating it from table data. Added complexity which was just never implemented and - given that SAP stopped doing serious work on SE24 around 10 years ago - probably never will be.

**Comment by HrFlorianHoffmann** [comment]
It's working, actually. Just make sure you enter the type's name and set it to public in the form view *before* editing it in the source code view.

![PublicTypesInSe24](https://user-images.githubusercontent.com/24736032/87910953-23d9a900-ca6b-11ea-9d39-682f130ac42e.PNG)

**Comment by Suncatcher** [comment]
Yes, that's the correct sequence for adding type. The problem seems to be resolved.
