### ISSUE TITLE
Are Clean ABAP Guidelines already covered by code inspector

### ISSUE THREAD

**Issue by MarcelHesen** [SAP/styleguides#166]
Hi all,
First of all forgive me if this is the wrong place to post. I choose this as it is something I would like to hear the community's opinion about.

So here goes:
In our company I would like to introduce the Clean ABAP guidelines. Additional to that it would be helpful to have the capability to check the code against these guidelines. Preferably we would do this using ATC/CI. I was thinking of writing some myself, but then again, we have an open source community... :-)

So does anyone know whether the guidelines are (partially?) covered by existing or custom code inspector classes? If so, where can they be found!

**Comment by pokrakam** [comment]
Good question! I don't believe there is a single ATC rule set specific to Clean Code. As I see it, coding standards are a very customer-individual decision, and I would imagine most customers will only be gradually implementing these guidelines in phases.
Another problem is that many rules depend on semantics and will be hard to implement technically. How could one check [Descend one level of abstraction](https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#descend-one-level-of-abstraction) without understanding the meaning?

That said, I like the idea of trying to create such a check. Aside from the SAP-Delivered ATC checks, there are also some very good tools out there that are also of use. I would imagine that with a well-defined ATC check variant, [abapLint](https://github.com/abaplint/abaplint) and [abapOpenChecks](https://github.com/abaplint/abaplint), you could probably cover 60-80% of this guide.

**Comment by flaiker** [comment]
https://github.com/SAP/code-pal-for-abap

**Comment by MarcelHesen** [comment]
Thx guys, for taking the trouble to answer.
Very useful pointers to (partial) solutions, great starting point for me to continue the search!
