### ISSUE TITLE
golden rules word and guideline pdf can not be open after download

### ISSUE THREAD

**Issue by jasonwangnanjing** [SAP/styleguides#169]
Hi Man,
golden rules word document and guideline pdf document can not be open after download.
May u please reupload them?

**Comment by mAltr** [comment]
Hi @jasonwangnanjing 

thanks for the hint. I checked all pdf files with current Adobe Acrobat Reader and the doc files with Office 365 and on my machine and it works without error :) Can you please get a bit more into detail? Does the error still happening? How did you download the files (git or web)? Which error did occur? Which programs to you use to open?

Have a nice day!
