### ISSUE TITLE
Unit test for IDoc development

### ISSUE THREAD

**Issue by krzysztofkuczek** [SAP/styleguides#173]
Hello,
I wonder if it's good place to ask such a questions, but I wonder what is best practice for implementation of unit tests covering custom out bound idoc generation.
Let say that we have implemented badi HRALE00OUTBOUND_IDOC, some additional segment is placed, and filled by custom code.
I can imagine writing kind of unit test abap report/or class , calling one of the fancy idoc creation FM, and looking into just generated idoc structure, but it's not fast nor clean solution.... And it will not cover idoc distribution, etc...
Do you have any experience in this area?
Kris

**Comment by schmelto** [comment]
@krzysztofkuczek I also wonder if this would be helpful but I think unit tests for a whole IDOC are out of scope and to difficult to implement.
For example currently I write a program modifying outgoing payment IDOCs. Unit tests would be nice but to implement those tests for all different possibilities would be a mess.
But yeah if there is an easy clean way I would definitely give it a try.

**Comment by WouterPeeters** [comment]
In the meanwhile I've worked for about 5 years in an environment where all code should have at least 1 unit test. Some thoughts to your questions:
- Always write your code in a class, if you are technically obligated to start in something else, I expect a single method call to your class where everthing else is handled. All logic should be in a class!
- IDOC's can perfectly be unit tested, just make a seperation between the Model logic and the Controller logic (MVC). Model logic is the pure code working with structures and fields, the Controller logic for me is mapping from IDOC it's abstract structures to normal structures. 

I would always Unit Test, but offcourse only if you have monitoring on failed unit tests + it's a team effort.

**Comment by pokrakam** [comment]
Concur with @WouterPeeters that this should be perfectly testable. The hidden benefit of unit testing is that it makes you structure your product code much better. 
What @krzysztofkuczek described is more integration testing. For outbound IDOCs the unit test is in your enhancement code. Along the lines of: 
- setup your preconditions:  selection of EDID4 entries and mock data
- call enhancement code
- Assert it adds segments with expected data
- repeat for various business cases or technical variants
This becomes easy if the code is well structured, e.g. User Exits go straight to classes.

**Comment by bjoern-jueliger-sap** [comment]
Appears to be a (completed) discussion about specific unit test practices, not an issue/proposal for the guide.
