### ISSUE TITLE
What are the pros and cons of typing interface method parameters generic to make the interface more accessible?

### ISSUE THREAD

**Issue by ChristianBreak** [SAP/styleguides#180]
I have an application that creates xml strings from abap structures using many different simple transformations and consequently many different abap structures.

I want to use a more flexible OO approach with an Interface to do this but due to the different structures the method signatures importing parameter is always different.

What are the pros and cons of typing the importing parameter generic instead so I can implement one method from one interface in each class handling the different transformations?

    INTERFACE if_transformer.
      METHODS transform_xml
        IMPORTING isource_structure TYPE REF TO data
        RETURNING VALUE(rxml_string) TYPE string.
    ENDINTERFACE. 

      ...
      
      CLASS material_transformer definition.
        PUBLIC SECTION.
          INTERFACES if_transformer.
      ENDCLASS.
      
      CLASS material_transformer IMPLEMENTATION.
      METHOD if_transformer~transform_xml.
        FIELD-SYMBOLS <structure> TYPE concrete_structure.
        ASSIGN isource_structure->* TO <structure>.
        ...
      ENDMETHOD.
      ENDCLASS.

**Comment by HrFlorianHoffmann** [comment]
I left an [answer to this question over on StackOverflow](https://stackoverflow.com/questions/66303449/what-are-the-pros-and-cons-of-typing-interface-method-parameters-generic-to-make/66319127#66319127).

**Comment by HrFlorianHoffmann** [comment]
Suggest to close this question - unless you'd like us to consider adding some details on these trains of thought?

**Comment by ChristianBreak** [comment]
I'm closing, thanks!
