### ISSUE TITLE
master vs. main

### ISSUE THREAD

**Issue by xtough** [SAP/styleguides#181]
Any plans to rename 'master' to 'main' yet?

**Comment by mAltr** [comment]
Don´t forget to add "slave", "blacklist", "whitelist", etc. 
Maybe it could be generic, to avoid critical verbs in general.

**Comment by HrFlorianHoffmann** [comment]
Will be done shortly, as described in https://github.com/github/renaming.

@mAltr we already scanned the repository for occurrences of controversial terms.

**Comment by mAltr** [comment]
@HrFlorianHoffmann Oh sorry, there was a misunderstanding from my side. I thought it was regarding adding a section to the guide avoid such words in abap, too.

**Comment by xtough** [comment]
@larshp FYI

**Comment by nununo** [comment]
> @HrFlorianHoffmann Oh sorry, there was a misunderstanding from my side. I thought it was regarding adding a section to the guide avoid such words in abap, too.

Maybe also a section with a guideline to avoid words like fuc*, shi*, c*nt, assh*le, h*re, p*mp*? :-)

**Comment by mAltr** [comment]
> > @HrFlorianHoffmann Oh sorry, there was a misunderstanding from my side. I thought it was regarding adding a section to the guide avoid such words in abap, too.
> 
> Maybe also a section with a guideline to avoid words like fuc*, shi*, c*nt, assh*le, h*re, p*mp? :-)

I think those words are essential (at least in my code) and are not related to the slavery wording discussion ;) 

https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by HrFlorianHoffmann** [comment]
`master` is now `main`
