### ISSUE TITLE
styleguide CODEOWNERS

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#185]
Suggest adding CODEOWNERS,
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

Something like below?

```
# fallback
* KlausHaeuptleSAP

# one line for each document
/abap-code-review/ @xtough
/clean-abap/ @HrFlorianHoffmann @KlausHaeuptleSAP
```

**Comment by xtough** [comment]
👍 What do you think, @HrFlorianHoffmann @KlausHaeuptleSAP
