### ISSUE TITLE
Grouping of method calls 

### ISSUE THREAD

**Issue by suynwa** [SAP/styleguides#199]
Is there a guideline about grouping of method calls using colon ':' ?

`CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL(: I_BUKRS ), I_GJAHR ).` v/s 

`CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( I_BUKRS ).`
`CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( I_GJAHR ).`

IMO, in this case the first option looks intuitive and easier on the eye.

**Comment by larshp** [comment]
see also https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-us/abenchained_statements_guidl.htm

**Comment by suynwa** [comment]
Thanks for pointing that out. So, i infer that chained method calls should be avoided.

Could this be added to the style guide with a reference to the ABAP documentation?

**Comment by pokrakam** [comment]
`CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( I_BUKRS && I_GJAHR ).`

**Comment by suynwa** [comment]
@pokrakam Good one, it is applicable in this case 👍🏼  I was looking for a guideline on using chained methods

**Comment by jordao76** [comment]
This kind of statement looks very _unnatural_, If only for the reason that the parenthesis don't match:

```abap
CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL(: I_BUKRS ), I_GJAHR ).
```

So I wouldn't recommend this syntax, and by extension wouldn't recommend chained statements for method calls. Clean ABAP is about making the code understandable and maintainable. Readability trumps convenience when writing the code. I wouldn't recommend this one either:

```abap
CL_ABAP_UNIT_ASSERT=>ASSERT_NOT_INITIAL( I_BUKRS && I_GJAHR ).
```

Concatenation is being abused to amalgamate variables to check if either one is initial. This is also hard for the reader. He has to _guess_ as to why concatenation is being used.

Also, you have to think about the readability of the tests when they _fail_. You want the error message of a failing test to be obvious and make it easy to pinpoint what is wrong with the code (or the test).

Then, I see some options:

1. Have separate calls as you shown before, but also use the `msg` parameter to have a clarifying message for when the assertion fails.
2. Put your variables in a structure that makes sense for your code, and assert that the structure is initial in one call, also using the `msg` parameter.
3. You can also create a custom assertion method that checks for a specific business-specific condition and in this case would take both variables as parameters and possibly do the 2 initial asserts inside (option 1).

**Comment by pokrakam** [comment]
@suynwa the guideline has been in the ABAP docs for some time, as Lars pointed out. I believe the point of this guide is not to replicate the existing documentation but to supplement it with a specific focus on Clean Code (and occasionally disagree with it 😀). In short: Chains can be useful in declarations but avoid in code.

@jordao76 I understand what you mean about concatenation, but for BUKRS+GJAHR I think it's clear enough that it's a compound key. Anyhow it was just a quick of the cuff alternative that is just as compact but easier to read without unbalanced parentheses.
To add option 4: Put multiple/complex asserts in their own method e.g. `assert_all_are_initial( ).`

**Comment by suynwa** [comment]
Thanks for the feedback @jordao76, @pokrakam.

It was just a simple example to highlight the usage of chained method calls. So, i didn't add the usual bells & whistles e.g., wrapping the assertions in individual methods
