### ISSUE TITLE
Slack access/invitations

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#2]
https://github.com/SAP/styleguides/blob/master/CONTRIBUTING.md
mentions
"
Join our Slack workspace sapcodestyleguides.slack.com if you want to discuss guidelines or possible changes without actually submitting anything.
"
but going to the page it says
"Don't have an account on this workspace yet?
Contact the workspace administrator for an invitation"

how to get an invitation?

**Comment by HrFlorianHoffmann** [comment]
Good one! I am new to Slack's free plan... Better after 01f50bde053dd0ddb7755284d44942176dc6e217?

**Comment by larshp** [comment]
yea, it will work

there are also some automatic inviters like https://abapgit-slackinviter.herokuapp.com/, but I'm not sure exactly what is required to set it up

closing
