### ISSUE TITLE
[rl-license_file-2] License doesn't seem to be compliant (e.g. Apache 2.0, CC-BY 4.0, MIT)!

### ISSUE THREAD

**Issue by HrFlorianHoffmann** [SAP/styleguides#204]
For details please see our wiki page at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-License(rl-license_file-XX)

**Comment by HrFlorianHoffmann** [comment]
This issue was created by a new linter from SAP that scans SAP's own open source repository for non-compliance to some company standards. Apparently, the linter finds that this licence should by CC BY 4.0 rather than CC BY 3.0. However, we were specifically advised to resort to CC BY 3.0 when we created this. Will clarify this with the internal process and tool owners.

**Comment by SebastianWolf-SAP** [comment]
Sorry, I obviously forgot to update this issue. That was clarified, the license can stay as it is.
