### ISSUE TITLE
[rl-readme_file-2] README is incomplete. Please check the following sections: Requirements, Download and Installation, Support, Licensing

### ISSUE THREAD

**Issue by HrFlorianHoffmann** [SAP/styleguides#205]
For details please see our wiki page at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-Readme(rl-readme_file-XX)

**Comment by HrFlorianHoffmann** [comment]
This issue was created by a new linter from SAP that scans SAP's own open source repository for non-compliance to some company standards. Apparently, the linter finds that the README.md in the root directory of this repository does not provide some section titles that should be standard for software repositories, such as "Requirements", "Download and Installation", and "Support". However, this repository does not provide any code - at least none that can be compiled, downloaded, installed, and run - so these sections don't make sense. Will clarify this with the internal process and tool owners.

**Comment by esjewett** [comment]
@HrFlorianHoffmann Is there an externally available version of that documentation linked above? If the linter is running on external repositories, that's probably a "must".

**Comment by bjoern-jueliger-sap** [comment]
Link to non-public source, appears to be inapplicable to repositories that do not contain source code anyway
