### ISSUE TITLE
RETURNING large tables is usually okay

### ISSUE THREAD

**Issue by webracer999** [SAP/styleguides#235]
I'm missing the reason why "RETURNING large tables is usually okay" (Clean ABAP).
The reason in my eyes is ABAPs  "Sharing Between Dynamic Data Objects" (https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenmemory_consumption_3.htm). So internal tables aren't copied in memory, when they don't differ.

Returning of large tables therefore effectively end in a logical "call by reference". Which can be observed with the debugger.

**Comment by larshp** [comment]
yea, also see https://blogs.sap.com/2017/07/30/the-mysteries-of-the-returning-parameter/

**Comment by N2oB6n-SAP** [comment]
That's correct, the reason being the copy-on-write mechanic with respect to the table data should be mentioned.
