### ISSUE TITLE
Wrong example for "Don't chain assignments"?

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/styleguides#268]
Chapter "Don't chain assignments" currently has the following two code snippets:

```
var2 = var3.
var1 = var3.
```
```
var1 = xsdbool( var2 = var3 ).
```

Can someone please explain to me what the `xsdbool` code snippet has to do with the topic? It doesn't make any sense to me to assign the boolean `abap_true` to `var1`. It has the value of `var2` and `var3`, but not necessarily a boolean and it is not necessarily true.

**Comment by ConjuringCoffee** [comment]
OK, thanks for the explanation. I believe this information could be better conveyed in the guideline. I have proposed a change to this section.

**Comment by rdibbern** [comment]
This issue is resolved by [22a5818](https://github.com/SAP/styleguides/commit/22a581898dd0b4d26e575c23b8acf87edb381e56) into SAP:main [on 25 Jul](https://github.com/SAP/styleguides/pull/269#event-7057034320)
