### ISSUE TITLE
CHECK vs RETURN, example

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#276]
in
https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#check-vs-return

the good example

```abap
METHOD read_customizing.
  IF keys IS NOT INITIAL.
    " do whatever needs doing
  ENDIF.
ENDMETHOD.
```

Might not be super good, especially it introduces nesting, https://twitter.com/JelenaAtLarge/status/1527775392790204416

I typically have code looking like

```abap
METHOD read_customizing.
  IF keys IS INITIAL.
    RAISE NEW...
  ENDIF.
    " do whatever needs doing
ENDMETHOD.
```

in the example it looks like a validation for input?

**Comment by ceedee666** [comment]
In my opinion which option to choose depends on the current situation. 
- If an empty ˋkeysˋ is a situation that should never happen I would also throw an exception. 
- If an empty ˋkeysˋ is a valid option throwing an exception is an anti pattern. In this case the Version with a ˋreturnˋ should be used.

**Comment by ceedee666** [comment]
Therefore the beginning of the paragraph should also be clarified. 

> There is no consensus on whether you should use CHECK or RETURN to exit a method if the input doesn't meet expectations.

**Comment by Sachinart** [comment]
@ceedee666 Either way, keeping a single IF statement in method is not a good practice. And I support @larshp using IF for raising the exception or using CHECK/RETURN statement and the placeholder for the logic when keys are not initial.

**Comment by Jelena-P** [comment]
Both examples below are valid, which one to use depends on the scenario and specific requirements. This part is not the matter of cleanliness.
```
METHOD read_customizing.
  IF keys IS INITIAL.
    RAISE NEW...
  ENDIF.
    " do whatever needs doing
ENDMETHOD.
```
or
```
METHOD read_document.
  IF keys IS INITIAL.
    RETURN.
  ENDIF.
    " do whatever needs doing
ENDMETHOD.
```
The main point is the **whole method** should never be wrapped in IF... ENDIF. That's anti-clean. :)

**Comment by pokrakam** [comment]
If it _really_ shouldn't happen (e.g. only through programmer error), then I'd even go as far as `assert`

There's another related (anti?)pattern:
```abap
if <someCondition>. 
  do stuff. 
  do things.
  ...
  more code.
  ...
else.
  raise exception ...
endif.
```

IMHO it is cleaner to invert the condition and do
```abap
if <notSomeCondition>. 
  raise exception ...
endif.
do stuff, party, whatever.
```

**Comment by ruthiel** [comment]
> If it _really_ shouldn't happen (e.g. only through programmer error), then I'd even go as far as `assert`
> 
> There's another related (anti?)pattern:
> 
> ```abap
> if <someCondition>. 
>   do stuff. 
>   do things.
>   ...
>   more code.
>   ...
> else.
>   raise exception ...
> endif.
> ```
> 
> IMHO it is cleaner to invert the condition and do
> 
> ```abap
> if <notSomeCondition>. 
>   raise exception ...
> endif.
> do stuff, party, whatever.
> ```

I agree with this approach!

**Comment by Jelena-P** [comment]
That's what I usually do too - put the shortest part of IF / exception first. Much easier to read IMHO.

**Comment by larshp** [comment]
I think this issue is still relevant, and it is common practice to follow the discussion in issues instead of pull requests

**Comment by larshp** [comment]
alternatively, I can follow the approach and roll back the changes in #277 with new changes?
