### ISSUE TITLE
protect main branch and require pull requests?

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#280]
Hi,
Suggest [protecting](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) the `main` branch and require pull requests for all changes.

Contributors will then get early feedback in the pull request regarding syntax or style/typos, instead of trial/error commits to the `main` branch directly.

Also check the https://github.com/SAP/styleguides/releases/download/latest/abap-code-review-guide.pdf for a suggested process for contributions to git

**Comment by KlausHaeuptleSAP** [comment]
Hi Lars,

has been changed :). Branch protection is now activated for future changes. 

Another question: Can you send me your new email address? I still have the old one.
