### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#3]
Hi,
First of all, thanks, very nice guide and thanks for sharing 👍 

Any thoughts on including links/recommendations regarding static analysis tools supporting the guidelines?

Eg.
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#omit-the-optional-keyword-exporting
is implemented by
https://docs.abapopenchecks.org/checks/30/

and some of
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#omit-the-parameter-name-in-single-parameter-calls
is found by
https://docs.abapopenchecks.org/checks/43/

**Comment by HrFlorianHoffmann** [comment]
Put some links together in https://github.com/SAP/styleguides/pull/9 but not sure this is the best format. It sure links the issues to the checks on a precise level, but it feels like there is some more general section missing that details what static code check tools we actually recommend. Some stuff is also covered in rarer Code Inspector checks, plus there are other projects that announced that they want to add static checks for clean code as well.

**Comment by larshp** [comment]
yeah, agree, need to consider the format, hmm

one approach is to add additional information in an collapsible section, example https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab, but the markdown format for this is not very nice IMHO

**Comment by HrFlorianHoffmann** [comment]
Added and merged.

**Comment by larshp** [comment]
https://github.com/SAP/styleguides/pull/32 merged, closing

**Comment by larshp** [comment]
perhaps also mention "ATC"? IMHO ATC is basically code inspector, but it depends on who you ask. Plus I guess the general SAP recommendation is to use ATC

**Comment by larshp** [comment]
links from abapOpenChecks documentation to this styleguide added in https://github.com/larshp/abapOpenChecks/commit/5e5262e802645ed334a0009987d2b735e90ebf24
