### ISSUE TITLE
Text on logo not readable in dark mode (Code Review Guide)

### ISSUE THREAD

**Issue by ConjuringCoffee** [SAP/styleguides#313]
The text on the image in the introduction of the code review guideline is not readable in Dark Mode:

![image](https://user-images.githubusercontent.com/72548231/232464227-e4a1cb92-8ebf-4212-bd8d-3c518ccf80be.png)

There's black text on a transparent background:

![image](https://user-images.githubusercontent.com/72548231/232464324-71d119be-c902-43bc-b655-1078b597bf48.png)

This is the image:

/SAP/styleguides/blob/main/abap-code-review/images/logo.svg

**Comment by xtough** [comment]
Valid point. Just realized the same when switching to dark mode. 
The text inside the SVG was a compromise of the former PDF export to get ASCIIDoc to print some sort of abstract on the title page. 
I will try to split this up again into SVG + separate text.

**Comment by larshp** [comment]
https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/ and/or https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/ might help

**Comment by xtough** [comment]
> https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/ and/or https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/ might help

Na, I think we would then need to provide 2 svg images for dark/light mode. The logo as such is not the issue, though. It is the text, which anyway does not belong into the SVG. 
I hope that #314 solves the issue.
