### ISSUE TITLE
Use READ-ONLY sparingly  - new abap command FINAL

### ISSUE THREAD

**Issue by foessleitnerj** [SAP/styleguides#336]
**Use READ-ONLY sparingly**
> Please link here to all relevant sections of the [Clean ABAP guide][(https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md)](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#use-read-only-sparingly)

**Description**
> At the end of the section, there is the comment "To avoid misunderstandings: Protecting variables .... " 

Since 7.57 it is possible to create Immutable Variables with FINAL
https://help.sap.com/doc/abapdocu_757_index_htm/7.57/en-US/index.htm?file=abenfinal_inline.htm

**Comment by rdibbern** [comment]
Please have a closer look into the [comment of Björn](https://github.com/SAP/styleguides/pull/299#issuecomment-1512691880) of the closed PR.

**Comment by bjoern-jueliger-sap** [comment]
Discussion of what to do with respect to final is in https://github.com/SAP/styleguides/issues/285 already, in addition to the PR linked by rdibbern above.
