### ISSUE TITLE
Clarify Show Message Text Shortcut

### ISSUE THREAD

**Issue by cawoodmonads** [SAP/styleguides#351]
The [docs](https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#dont-duplicate-message-texts-as-comments) mention:
> The modern IDEs give you easy ways to see the text behind a message, for example in the ABAP Development Tools, mark the message ID and press Shift+F2.

I cannot confirm this in the latest ADT - it does not work and I can't find any documentation on it.

![image](https://github.com/SAP/styleguides/assets/163100156/22d46b2b-002c-41ea-82d3-33e55754dc09)

**Comment by fabianlupa** [comment]
I think the hotkey is simply `F2` not `Shift + F2` and this is an error in the styleguide. Unless maybe it's different on MacOS.

**Comment by pokrakam** [comment]
I can confirm MacOS uses `F2` as well, have submitted a correction.
