### ISSUE TITLE
Mentioning of Avalon

### ISSUE THREAD

**Issue by timostark** [SAP/styleguides#36]
Dear All,

First thanks for that really usable best-practice style guide. This is really something which was missing in the ABAP world.

One request: In our projects we were still struggling to create test-doubles / identify a usable test-double-framework for AMDPs. In the best-practice style guide you are mentioning the tool "Avalon". Honestly I am not aware of this tool, and a quick search on https://launchpad.support.sap.com, or help.sap.com didn't bring anything up.
Can you provide any link for this tool?

![image](https://user-images.githubusercontent.com/19237828/57620115-1c299500-7588-11e9-8597-539e20a76561.png)

Thanks a lot,
Timo

**Comment by thomham** [comment]
This is an internal tool - the predecessor of the CDS test double framework and should not be mentioned in the document.

**Comment by HrFlorianHoffmann** [comment]
Removed the mention with https://github.com/SAP/styleguides/pull/38. Didn't catch this detail when moving the content from the SAP-internal repository to this public one; sorry.

**Comment by HrFlorianHoffmann** [comment]
Testing AMDPs is - as of now - a gap.

Avalon copies the original AMDP, modifying its code to replace references to the real dependencies to generated mocks. While this is a powerful means and allows testing some artifacts that the CDS Test Double Framework doesn't support, it is also a quite fragile solution.

We hope to be seeing some unit test tool for AMDPs in the future, but can't promise anything.
