### ISSUE TITLE
Golden Rules: example for functional constructs does not work in ABAP

### ISSUE THREAD

**Issue by kaman-thah** [SAP/styleguides#41]
The example for functional constructs ("index += 1") does not work in ABAP. You will still have to use "index = index + 1" or "ADD 1 TO index"...

**Comment by larshp** [comment]
works in 754 or above, as noted in the document,

```abap
index += 1.         " >= NW 7.54
```

**Comment by kaman-thah** [comment]
Oh, OK. Missed that. Thanks!
