### ISSUE TITLE
Consider splitting into multiple files

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#5]
Hi,
The Markdown file is current 4400+ lines, have you considered splitting this into multiple files? This might make it easier to read the change history plus decreases the possibility for merge conflicts.

GitHub offers Jekyll for static site analysis so its possible to present the guide in a format different than the file structure, https://help.github.com/en/articles/using-jekyll-as-a-static-site-generator-with-github-pages

**Comment by KlausHaeuptleSAP** [comment]
With regards to Jekyll: At the current stage, we want to focus on the content. Besides, we felt that it makes contributions more cumbersome, since the contributor needs to setup an environment in order to see how the final result looks like.

**Comment by larshp** [comment]
okay, closing
