### ISSUE TITLE
Open SQL: Obsolete Host Variables

### ISSUE THREAD

**Issue by larshp** [SAP/styleguides#6]
Suggest adding a section corresponding to https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenopen_sql_hostvar_obsolete.htm

**Comment by HrFlorianHoffmann** [comment]
How about https://github.com/SAP/styleguides/pull/31?

**Comment by larshp** [comment]
looks good to me 👍

**Comment by HrFlorianHoffmann** [comment]
Merged.
