### ISSUE TITLE
Replace internal links

### ISSUE THREAD

**Issue by flaiker** [SAP/styleguides#7]
Hi,

there seem to be some SAP internal links in the document. Could these be replaced with public ones?
https://github.com/SAP/styleguides/search?q=sap.corp&unscoped_q=sap.corp

**Comment by HrFlorianHoffmann** [comment]
Removed the "Public" section with https://github.com/SAP/styleguides/commit/9894f7aaa7a5fdce587a0e16888fbc454790ba87. We originally added that section when it still said "Internal", to make people aware of whom they were allowed to share the content with. Now that the whole repository is shared as Open Source, it is not really needed anymore.

**Comment by KlausHaeuptleSAP** [comment]
Additionally we replaced internal links with relative links.
