### ISSUE TITLE
NOT ... IS VS IS NOT

### ISSUE THREAD

**Issue by thanan2** [SAP/styleguides#72]
This is a minor topic that I haven't seen covered in the guide.

Isn't it more readable? 
   IF variable IS NOT INITIAL.

than,
   IF NOT variable IS INITIAL.

I have always found the second example more confusing and less related to the natural language. What do you think? 
By the way, congratulations for this guide, it is awesome.

**Comment by pixelbaker** [comment]
+1

**Comment by flaiker** [comment]
Here's the guideline from the keyword documentation regarding this topic:
https://help.sap.com/doc/abapdocu_753_index_htm/7.53/en-US/index.htm?file=abenalternative_langu_guidl.htm
> The addition NOT of the relational operators BETWEEN, IN, IS ASSIGNED, IS BOUND, IS INSTANCE OF, IS INITIAL, and IS SUPPLIED is a better option than the identical Boolean operator NOT, for improved readability. For example, the expression a IS NOT INITIAL is easier than the logically identical expression NOT a IS INITIAL. This corresponds to the definition of comparison expressions, where a <> b is more intuitive than NOT a = b.

**Comment by HrFlorianHoffmann** [comment]
Created a Pull Request with your suggestion. Leaving it open for another day for reviewing the wording.

**Comment by HrFlorianHoffmann** [comment]
Merged the new section. Suggest to close the issue.

**Comment by marcellourbani** [comment]
@thanan2 
I agree completely.
The only catch (not relevant for this document) is that on very old systems IS NOT doesn't work.

If your code must work on 6.x
