### ISSUE TITLE
OpenSql: CAST with SUM aggregation

### ISSUE THREAD

**Issue by fischicr7** [SAP/styleguides#82]
Hey Guys,

is it possible to do sth. like this in sql statement:

SELECT  key, CAST( SUM( value AS DEC( 13,2 ) ) ) AS value__long..

I want to avoid an overflow without changing the table field. 
Would be nice to do this on Hana in the future, without adding the value on application server in my method. Couldn´t find anything useful yet.

Kind regards
Daniel

**Comment by HrFlorianHoffmann** [comment]
Wrong resource. :-) You'll get better answers to your question [onSAP Answers](https://answers.sap.com/index.html) and [on StackOverflow for the tag \[abap\]](https://stackoverflow.com/questions/tagged/abap). If you are sure, this feature doesn't exist, you can also create a support ticket.
